<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3400" started-at="2018-08-07T15:22:32Z" finished-at="2018-08-07T15:22:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3400" started-at="2018-08-07T15:22:32Z" finished-at="2018-08-07T15:22:35Z">
      <class name="com.agentaDemo.AgentaTestCase.NotReady_Conference_Popup">
        <test-method status="PASS" signature="setObject()[pri:0, instance:com.agentaDemo.AgentaTestCase.NotReady_Conference_Popup@679b62af]" name="setObject" is-config="true" duration-ms="2786" started-at="2018-08-07T20:52:32Z" finished-at="2018-08-07T20:52:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setObject -->
        <test-method status="FAIL" signature="to_validate_Conference_for_three_User_in_Not_Ready_with_PopUp(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.agentaDemo.AgentaTestCase.NotReady_Conference_Popup@679b62af]" name="to_validate_Conference_for_three_User_in_Not_Ready_with_PopUp" duration-ms="99" started-at="2018-08-07T20:52:35Z" data-provider="conference" finished-at="2018-08-07T20:52:35Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
The data provider is trying to pass 15 parameters but the method com.agentaDemo.AgentaTestCase.NotReady_Conference_Popup#to_validate_Conference_for_three_User_in_Not_Ready_with_PopUp takes 12]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 15 parameters but the method com.agentaDemo.AgentaTestCase.NotReady_Conference_Popup#to_validate_Conference_for_three_User_in_Not_Ready_with_PopUp takes 12
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1229)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1122)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- to_validate_Conference_for_three_User_in_Not_Ready_with_PopUp -->
      </class> <!-- com.agentaDemo.AgentaTestCase.NotReady_Conference_Popup -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
